services:
  - type: web
    name: inventory-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn inventory_systems.wsgi --log-file -
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

databases:
  - name: inventory-db
    plan: free
