# Generated by Django 4.0 on 2025-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_create_public_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='folder',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('domain', 'folder')},
        ),
    ]
