# Generated by Django 6.0.2 on 2026-02-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_domain_folder_alter_domain_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='schema_name',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
