# Generated by Django 4.0 on 2025-08-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The tenant (company) this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.client'),
        ),
    ]
