# Generated by Django 4.0 on 2025-10-21 09:12

# accounts/migrations/0002_create_superuser.py

import os
from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()

    # Get credentials from environment variables
    username = os.environ.get('uzo')
    email = os.environ.get('udike98@gmail.com')
    password = os.environ.get('Getrichortrydying50')

    # Check if a superuser already exists
    if User.objects.filter(is_superuser=True).exists():
        print('Superuser already exists, skipping creation.')
        return

    # Check if all required environment variables are set
    if not all([username, email, password]):
        print('Admin credentials not found in environment variables. Skipping superuser creation.')
        return

    # Create the superuser
    User.objects.create_superuser(username=username, email=email, password=password)
    print(f'Superuser "{username}" created successfully!')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_company'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
