# Generated by Django 4.0 on 2025-10-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_company'),
        ('accounts', '0005_merge_20251021_1117'),
    ]

    operations = [
    ]
