# Generated by Django 6.0.2 on 2026-02-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_reset_admin'),
        ('tenants', '0004_remove_client_schema_name_delete_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(default=1, help_text='The tenant (company) this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.client'),
            preserve_default=False,
        ),
    ]
