"""
Django settings for inventory_systems project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# Build paths inside the project like this: BASE_DIR / 'subdir'.


import os
from pathlib import Path
import environ
import dj_database_url

# ------------------------------------------------------------
# BASE / ENV
# ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("DJANGO_SECRET_KEY", default="fallback-secret-key")
DEBUG = env.bool("DEBUG", default=False)

# ------------------------------------------------------------
# HOSTS / CSRF (Render + Railway + Local)
# ------------------------------------------------------------
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "inventory-sys-ntjc.onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    f"https://{env('RENDER_EXTERNAL_HOSTNAME','')}",
    "https://inventory-sys-ntjc.onrender.com",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ------------------------------------------------------------
# MULTI-TENANCY (django-tenants)
# ------------------------------------------------------------
SHARED_APPS = [
    "django_tenants",          # MUST be first
    "tenants",
    "accounts",                # shared
    "stock",                   # shared
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "corsheaders",
    "pwa",
]

TENANT_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "djoser",
]

INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "tenants.Client"
TENANT_DOMAIN_MODEL = "tenants.Domain"
TENANT_URLCONF = "inventory_systems.tenant_urls"
TENANT_BASE_URLCONF = "inventory_systems.tenant_urls"
TENANT_SUBFOLDER_PREFIX = "clients"

DATABASE_ROUTERS = ["django_tenants.routers.TenantSyncRouter"]

# ------------------------------------------------------------
# DATABASE (Neon PostgreSQL)
# Fixes "cursor already closed"
# ------------------------------------------------------------
DATABASES = {
    "default": dj_database_url.config(
        default=env("DATABASE_URL"),
        conn_max_age=60,              # Keep connection alive
        ssl_require=True,
    )
}

# Use django-tenants backend
DATABASES["default"]["ENGINE"] = "django_tenants.postgresql_backend"

# Connection stabilizers for Neon (prevents cursor drops)
DATABASES["default"]["OPTIONS"] = {
    "sslmode": "require",
    "connect_timeout": 10,
    "keepalives": 1,
    "keepalives_idle": 20,
    "keepalives_interval": 20,
    "keepalives_count": 5,
}

# ------------------------------------------------------------
# MIDDLEWARE (Correct order for django-tenants)
# ------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # Session must load BEFORE tenant middleware
    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",

    # Tenant middleware here (NOT at the top)
    "django_tenants.middleware.TenantSubfolderMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "inventory_systems.urls"

# ------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "inventory_systems.wsgi.application"

# ------------------------------------------------------------
# AUTH / JWT
# ------------------------------------------------------------
AUTH_USER_MODEL = "accounts.CustomUser"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
}

LOGIN_URL = "/api/accounts/login/"

# ------------------------------------------------------------
# STATIC FILES (Render)
# ------------------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ------------------------------------------------------------
# CORS
# ------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True

# ------------------------------------------------------------
# PWA
# ------------------------------------------------------------
PWA_APP_NAME = "Inventory App"
PWA_APP_DESCRIPTION = "Offline-enabled Inventory Management System"
PWA_APP_THEME_COLOR = "#000000"
PWA_APP_BACKGROUND_COLOR = "#ffffff"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_START_URL = "/"
PWA_APP_ORIENTATION = "portrait"
PWA_APP_ICONS = [
    {
        "src": "/static/images/my_app_icon.jpg",
        "sizes": "512x512",
    }
]

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, "static", "serviceworker.js")

# ------------------------------------------------------------
# TIMEZONE
# ------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Lagos"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------
# LOGGING (Render stdout)
# ------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



